enum Scopes {
    FULL_DRIVE,
    DRIVE_READONLY,
    DRIVE_APPFOLDER,
    DRIVE_APPS_READONLY,
    DRIVE_FILE,
    DRIVE_INSTALL,
    DRIVE_METADATA,
    DRIVE_METADATA_READONLY,
    DRIVE_PHOTOS_READONLY,
    DRIVE_SCRIPTS
}
export default Scopes;